version: '3'
services:
    app:
        deploy:
            replicas: 1
        env_file: env.production

    db:
        env_file: env.production

    proxy:
        image: 'bfabio/pa-dashboard-backend-proxy:latest'
        build:
            context: caddy/
            dockerfile: Dockerfile
        depends_on:
            - app
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
