# Used by DockerHub automated testing
# https://docs.docker.com/docker-hub/builds/automated-testing/

version: '3'
services:
    sut:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        env_file: env.test
        environment:
            RAILS_ENV: test
        command: bin/rails test
        depends_on:
            - db

    db:
        image: 'postgres:12'
        env_file: env.test
