version: '3'
services:
  app:
    env_file: env.test
    environment:
      RAILS_ENV: test
    depends_on:
      - postgres

  postgres:
    image: 'postgres:11'
    env_file: env.test
    restart: unless-stopped
