version: '3'
services:
  app:
    env_file: env.development
    environment:
      RAILS_ENV: development
    volumes:
      - 'gems:/app/vendor/bundle'
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: 'postgres:11'
    env_file: env.development
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    restart: unless-stopped

volumes:
  gems:
  pgdata:
