version: '3'
services:
    app:
        image: "bfabio/pa-dashboard-backend:${TAG:-latest}"
        build:
            context: ..
            dockerfile: docker/Dockerfile
        depends_on:
            - db
        ports:
            - '3000:3000'
        restart: unless-stopped

    db:
        image: 'postgres:12'
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    pgdata:
